### ISSUE TITLE
Enabled and disabled search options look (almost) the same

### ISSUE THREAD

**Issue by bersbersbers** [huacat1017/huacat.office-theme#14]
This is all search options in one state:

![image](https://user-images.githubusercontent.com/12128514/155936860-dc7190e6-d7f9-4037-abe9-01350dbaeda0.png)

This is the same screenshot after clicking each option once:

![image](https://user-images.githubusercontent.com/12128514/155936931-c42c41ce-7d25-4cd2-beaf-f14ff420b666.png)

Not sure if I should see a difference, but I don't. Quickly switching back and forth between the images shows some very very *very* faint difference - I think the contrast should be improved.

**Comment by huacat1017** [comment]
Sorry for late replying.
|1.44(install on my USB)|1.79(now)|
|-|-|
|<img width="229" alt="1 44" src="https://github.com/huacat1017/huacat.office-theme/assets/57604590/ab89ced3-ec26-4f49-b5cf-117427737987">|<img width="242" alt="1 79" src="https://github.com/huacat1017/huacat.office-theme/assets/57604590/354c3ea2-9a28-4dbc-b3bd-bcb3e29dde79">|

The problem occured before VSCode update its search bar style (add border) because I don't specify the color.
I will specify the color on the next update although VSCode automatically added the border to it.
Thank you for reporting!

**Comment by huacat1017** [comment]
I updated the extension(1.2.0). Enjoy the new search UI!

**Comment by bersbersbers** [comment]
Much better, thanks :)
